spring:
  application:
    name: onseju

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE
      org.apache.rocketmq: INFO
      org.scoula.three_people: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  ki:
    appKey: ${KOREAINVEST_CLIENT_ID}
    appSecret: ${KOREAINVEST_CLIENT_SECRET}
    accountNo: ""

rocketmq:
  name-server: localhost:9876
  producer:
    group: trade-producer-group
    send-message-timeout: 3000
  consumer:
    group: trade-persistence-group
