spring:
  application:
    name: onseju

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

  messaging:
    rocketmq:
      name-server: ${ROCKETMQ_NAME_SERVER}
      producer:
        group: ${ROCKETMQ_PRODUCER_GROUP}
        send-message-timeout: ${ROCKETMQ_SEND_MESSAGE_TIMEOUT}
  server:
    instance:
      id: ${SERVER_INSTANCE_ID}


management:
  endpoints:
    web:
      exposure:
        include: prometheus


kis:
  appKey: ${KIS_APP_KEY}
  appSecret: ${KIS_SECRET_KEY}
  approval: ${KIS_APPROVAL_KEY}
  token: ${KIS_TOKEN}